pluginManagement {
    repositories {
        maven {
            url = uri("https://pkgs.dev.azure.com/akeliuseducation/_packaging/akeliuseducation/maven/v1")
            credentials {
                username = settings.findProperty("akeliuseducationUsername")
                password = settings.findProperty("akeliuseducationPassword")
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
rootProject.name = 'university-statistic-core-library'
