pluginManagement {
    repositories {
        maven {
            url = uri("https://pkgs.dev.azure.com/akeliuseducation/_packaging/akeliuseducation/maven/v1")
            credentials {
                username = "akeliuseducation"
                password = System.getenv("AZURE_ARTIFACTS_PASSWORD")
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
rootProject.name = 'university-statistic-core-library'
